services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    # command: docker run --name mongodb -d -p 27017:27017 -v mongo-data:/data/db/ mongodb/mongodb-community-server:5.0.8-ubuntu2004
    environment:
        NODE_ENV: production
        # NODE_ENV: development
        MONGO_LOCAL_URI: mongodb://192.168.43.51:27017/test
        MONGO_REMOTE_URI: mongodb://10.0.0.4:27017/test
        APP_PORT: 8080
        DB_PORT: 27017
        JWT_SECRET: SECRET-KEY-API-V2
    networks:
      - mern-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    environment:
        NODE_ENV: production
        # NODE_ENV: development
    networks:
      - mern-network

  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   networks:
  #     - mern-network
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: example
  #     ME_CONFIG_MONGODB_URL: mongodb://192.168.43.51:27017/test
  #     ME_CONFIG_BASICAUTH: false
  #   # depends_on:
  #   #   - backend

networks:
  mern-network: 
    driver: bridge
